configParam: git-inner-test service-front-query configParam

spring:
  datasource:
    url: jdbc:mysql://192.168.1.225:3306/db_ctp?useUnicode=true&characterEncoding=utf-8&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Hongkong
    username: block
    password: pwd123
    driver-class-name: com.mysql.cj.jdbc.Driver
    #type: com.alibaba.druid.pool.DruidDataSource
    type: com.zaxxer.hikari.HikariDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 200
    maxWait: 60000
  # redis配置，以下有默认配置的也可以使用默认配置
  redis:
    host: 192.168.1.217
    port: 6379
    password: dami123
    timeout: 10000
    database: 0
    pool:
      max-active: 500
      max-idle: 50
      max-wait: -1
      min-idle: 10

  rabbitmq:
    username: dami
    password: 123456
    virtual-host: dami
    addresses: 192.168.1.13:5672
    listener:
      auto-startup: true
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.ctp.jarmodel.model
  configuration:
    map-underscore-to-camel-case: true

#logstash:
#  address: 192.168.1.212
#  port: 5044
#logging:
#  level: info
#  config: classpath:logback/logback-default-inner-test.xml
## 分页配置
#pagehelper:
#  helper-dialect: mysql
#  reasonable: true
#  support-methods-arguments: true
#  params: count=countSql

# 日志配置
#logging:
#  level: error
#  config: classpath:logback/logback-coinlim-prod.xml

# 暴露监控端点
management:
  health:
    db:
      enabled: false
    mail:
      enabled: false
    redis:
      enabled: false
    mongo:
      enabled: false
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details:ALWAYS
endpoints:
  actuator:
    enabled: true
  shutdown:
    enabled: false
legeal_digit: 2
small_hide: 10
addr_add_store: 10
addr_lower_warning: 50
url:
  service-business-walleteth: http://192.168.1.216:60002
  service-business-wallet-omni: http://192.168.1.216:60003
  service-business-wallet-zxt: http://192.168.1.216:60007
  service-business-wallet-edrc: http://192.168.1.216:60006
  service-business-wallet-ilcoin: http://192.168.1.216:60008
  service-business-wallet-obsr: http://192.168.1.216:60005
  service-business-wallet-ltc: http://192.168.1.216:60009
  service-business-wallet-xrp: http://192.168.1.216:60010
  service-business-wallet-eos: http://192.168.1.216:60087
  service-business-wallet-wgr: http://192.168.1.216:60004
  service-business-wallet-antra: http://192.168.1.216:60001


