configParam: git-inner-test service-business-tradingview configParam

spring:
  datasource:
    url: jdbc:mysql://52.82.80.65:3306/db_ctp?useUnicode=true&characterEncoding=utf-8&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Hongkong
    username: root
    password: Gd753951.
    driver-class-name: com.mysql.cj.jdbc.Driver
    #type: com.alibaba.druid.pool.DruidDataSource
    type: com.zaxxer.hikari.HikariDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
  # redis配置，以下有默认配置的也可以使用默认配置
  redis:
    host: 161.189.145.104
    port: 6379
    password: Gd123
    timeout: 10000
    database: 6
    pool:
      max-active: 500
      max-idle: 50
      max-wait: -1
      min-idle: 10
  rabbitmq:
    username: admin
    password: Qq122345
    virtual-host: admin
    addresses: 172.18.9.204:5672
    listener:
      auto-startup: true
  mail:
    host: smtp.mxhichina.com
    port: 587
    username: 1231345@coinlim.com
    password: 111
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  elasticjob:
    # 分布式任务协调依赖zookeeper
    zookeeper:
      server-lists: 172.18.9.5:2181
      namespace: vonechain-job
    # 普通任务
    simples:
      ScheduleGenTvData:
        job-class: com.ctp.servertradingview.schedule.ScheduleGenTvData
        # 从0秒开始每隔一分钟执行一次
        cron: 0 */1 * * * ?
        overwrite: true
        sharding-total-count: 10
        sharding-item-parameters: 0=service1,1=service2,2=service3,3=serivce4,4=service5,5=service6,6=service7,7=service8,8=service9,9=service10
        monitorExecution: false
        #eventTraceRdbDataSource: dataSource
        failover: true
        disabled: false
        jobParameter: test
        description: tradingview data for min
      ScheduleGenTvDataDays:
        job-class: com.ctp.servertradingview.schedule.ScheduleGenTvDataDays
        # 从0秒开始每隔一天执行一次
        # cron: 0 0 0 1/1 * ? 
        cron: 0 0 1 * * ?
        overwrite: true
        sharding-total-count: 3
        sharding-item-parameters: 0=service1,1=service2,2=service3
        monitorExecution: true
        eventTraceRdbDataSource: dataSource
        failover: true
        disabled: false
        jobParameter: test
        description: tradingview data for day
      ScheduleGenTvDataHours:
        job-class: com.ctp.servertradingview.schedule.ScheduleGenTvDataHours
        # 从0秒开始每隔一小时执行一次
        # cron: 0 0 0/1 * * ? 
        cron: 0 0 */1 * * ?
        overwrite: true
        sharding-total-count: 3
        sharding-item-parameters: 0=service1,1=service2,2=service3
        monitorExecution: true
        eventTraceRdbDataSource: dataSource
        failover: true
        disabled: false
        jobParameter: test
        description: tradingview data for hour

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.ctp.jarmodel.model
  configuration:
    map-underscore-to-camel-case: true

multipart:
  maxFileSize: 2Mb
  maxRequestSize: 1000Mb

# 日志配置
#logging:
#  level: error
#  config: classpath:logback/logback-coinlim-prod.xml

#logstash:
#  address: 172.31.36.133
#  port: 5000
#logging:
#  level: info
#  config: classpath:logback/logback-default-coinlim-prod.xml

# 暴露监控端点
management:
  health:
    db:
      enabled: false
    mail:
      enabled: false
    redis:
      enabled: false
    mongo:
      enabled: false
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details:ALWAYS
endpoints:
  actuator:
    enabled: true
  shutdown:
    enabled: false
