configParam: git-inner-test service-business-order configParam

spring:
  datasource:
    url: jdbc:mysql://52.82.80.65:3306/db_ctp?useUnicode=true&characterEncoding=utf-8&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Hongkong
    username: root
    password: Gd753951.
    driver-class-name: com.mysql.cj.jdbc.Driver
    #type: com.alibaba.druid.pool.DruidDataSource
    type: com.zaxxer.hikari.HikariDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
  # redis配置，以下有默认配置的也可以使用默认配置
  redis:
    host: 161.189.145.104
    port: 6379
    password: Gd123
    timeout: 10000
    database: 6
    pool:
      max-active: 500
      max-idle: 50
      max-wait: -1
      min-idle: 10
  rabbitmq:
    username: admin
    password: Qq122345
    virtual-host: admin
    addresses: 172.18.9.204:5672
  mail:
    host: smtp.mxhichina.com
    port: 587
    username: 1231345@coinlim.com
    password: 111
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.ctp.jarmodel.model
  configuration:
    map-underscore-to-camel-case: true

BitCoinTransfer:
  key: bitcoinTransfer
EthMentionCoin:
  key: ethMentionCoinKey
LTCCoin:
  key: ltcTransfer
xrpCoin:
  key: xrpMentionCoinKey
eosCoin:
  key: eosMentionCoin

#logstash:
#  address: 172.31.36.133
#  port: 5000
#logging:
#  level: info
#  config: classpath:logback/logback-default-coinlim-prod.xml

# 暴露监控端点
management:
  health:
    db:
      enabled: false
    mail:
      enabled: false
    redis:
      enabled: false
    mongo:
      enabled: false
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details:ALWAYS
endpoints:
  actuator:
    enabled: true
  shutdown:
    enabled: false
    
com:
  mqtt:
    outbound:
      url: tcp://192.168.1.13:1883
      clientId: ctp-server
      username: dami
      password: dami123
      qos: 0
      cleanSession: false
      connectionTimeout: 60
      keepAliveInterval: 30
